name: HA Test (Apache CGI)
version: "1.2.4"
slug: hatest
description: Simple Apache + CGI test add-on
url: "https://github.com/fullduplexnl/hatest/tree/main/hatest"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
map:
  - config:ro
ports:
  "8080/tcp": 8080
ingress: false
panel_icon: mdi:web

# Handige link in de UI
webui: "http://[HOST]:[PORT:8080]/"

